# Generated by Django 3.2.9 on 2021-12-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_town_or_city',
            new_name='default_city',
        ),
    ]
