# Generated by Django 3.2.9 on 2021-11-17 14:20

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products_others_bought',
            field=models.CharField(blank=True, default=products.models.Product.get_default_products_others_bought, max_length=254, null=True),
        ),
    ]
