# Generated by Django 3.2.9 on 2021-12-09 19:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211206_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.0'), '0.0'), (Decimal('0.5'), '0.5'), (Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=2, default=Decimal('3.0'), max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_review',
            field=models.TextField(max_length=200),
        ),
    ]
